nameOverride: "__APPNAME__"
domain: "__DOMAIN__"
hostName: "__EKSHOSTNAME__"
appPath: "__APPNAME__"
image:
  repository: "__ARTIFACTORYREGISTRY__.__ARTIFACTORYBASEURL__/__ARTIFACTORYDOMAIN__/__ARTIFACTORYPROJECT__"
  tag: "__ARTIFACTORYTAG__"
deployment:
  livenessProbe:
    failureThreshold: 20
    initialDelaySeconds: 60
    periodSeconds: 5
    successThreshold: 1
    tcpSocket:
      port: 8080
  readinessProbe:
    failureThreshold: 5
    initialDelaySeconds: 60
    periodSeconds: 20
    successThreshold: 1
    tcpSocket:
      port: 8080
env:
  normal:
    - name: "BASE_PATH"
      value: "/__APPNAME__"
    - name: "ENV"
      value: "__ENV__"
    - name: "LOG_LEVEL"
      value: "__LOG_LEVEL__"
    - name: "WEB_APP_DEBUG"
      value: "__DEBUG_FLAG__"
    - name: "WEB_APP_VERSION"
      value: "v1"
    - name: "WEB_APP_TITLE"
      value: "Canvas Tools"
    - name: "WEB_APP_DESCRIPTION"
      value: "Description here"
    - name: "SSO_SP_ENTITY_ID"
      value: "__SSO_SP_ENTITY_ID__" # https://dev-ats-pub.ucsd.edu
    - name: "SSO_IDP_ENTITY_ID"
      value: "__SSO_IDP_ENTITY_ID__" # https://dev-ats-pub.ucsd.edu
    - name: "SSO_LOGIN_URL"
      value: "__SSO_LOGIN_URL__"
    - name: "SSO_LOGOUT_URL"
      value: "__SSO_LOGOUT_URL__"
    - name: "APIM_TOKEN_URL"
      value: ""
    - name: "APIM_BASE_URL"
      value: ""
    - name: "SSO_REDIS_SESSION_PREFIX"
      value: "ati_canvas_tools"
    - name: "DATABASE1_URL"
      value: "__DATABASE1_URL__"
  secret:
    - name: "TEST_PASSWORD"
      value: "__TEST_PASSWORD__"
    - name: "APIM_CLIENT_KEY"
      value: "emptyclientkey"
    - name: "APIM_SECRET_KEY"
      value: "emptysecretkey"
    - name: "SSO_SECRET_CERT"
      value: "__SSO_SECRET_CERT__"
    - name: "REDIS_URL"
      value: "__REDIS_URL__" # redis://redis-session-campus.1kfkvu.0001.usw2.cache.amazonaws.com:7007

